# Documentation available at https://expeditor-docs.es.chef.io/

github:
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"

# Slack channel in Chef Software slack to send notifications about Expeditor actions
slack:
  notify_channel: habitat-notify

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Exclude from Changelog"

subscriptions:
  - workload: pull_request_opened:{{agent_id}}:*
    actions:
      - bash:.expeditor/welcome_comment.sh

changelog:
  categories:
    - "X-change": "Behavioral Changes"
    - "X-feature": "New Features & Enhancements"
    - "X-fix": "Bug Fixes"

github:
  release_branch:
    - master:
        # Version constraint at this point is arbitrary but represents 1.0.0
        version_constraint: 1*

pipelines:
  - verify:
      # Adding a comment to do a thing
      description: Pull Request validation tests
  - website:
      description: Deploy the website
      definition: .expeditor/website.pipeline.yml
      trigger: pull_request
